### ISSUE TITLE
Plugin disables category selection

### ISSUE THREAD

**Issue by ghost** [xxsimoxx/stats-for-update-manager#1]
When I have your plugin activated I lose the checkboxes on post categories.

![cc2](https://user-images.githubusercontent.com/46998578/71570353-cdd20200-2b28-11ea-9143-ee85ea9ce11e.jpg)

If plugin is deactivated they come back.

![cat1](https://user-images.githubusercontent.com/46998578/71570377-e3472c00-2b28-11ea-811b-d7618737fab0.jpg)

**Comment by xxsimoxx** [comment]
Thank you!
Seems some CSS is appearing where it should not...
Surely I'll fix in a few hours.

**Comment by xxsimoxx** [comment]
Thank you for reporting! Now it should be fixed.
