### ISSUE TITLE
Shortcodes for frontend display of stats

### ISSUE THREAD

**Issue by johnalarcon** [xxsimoxx/stats-for-update-manager#10]
# Description

I'm proposing the addition of a couple shortcodes that will allow frontend display of various stats. This would be handy to let potential users see how many others have a given plugin installed. The shortcodes can then be used in content areas, widgets, or theme templates – or in other marketing efforts. I've submitted a PR #11 which implements this functionality.
 
### [sfum-installs]

The above shortcode would return an integer depicting the total number of all installations (of all plugins) across the web. End users could use it in a sentence:
> Code Potent plugins have [_n_] active installations!

### [sfum-installs id="my-plugin-folder/my-plugin-file.php"]

Building on the first example, an argument is contemplated here. This shortcode would return an integer depicting the total number of installs for the plugin with the given `identifier` argument. End users could use it in a sentence:
> My Awesome Plugin has [_n_] active installations!

### [sfum-domains]

This shortcode would return an integer depicting the number of unique domains using all of the developer's plugins. End users could use it in a sentence: 

> Code Potent is running on [_n_] sites!

## Have you already some code that could help?
- [x] Yes
- [ ] No

**Comment by xxsimoxx** [comment]
Beautiful!
Merged #11!
Thank you very much!
