### ISSUE TITLE
Admin notice hijacks the dashboard

### ISSUE THREAD

**Issue by johnalarcon** [xxsimoxx/stats-for-update-manager#12]
**Describe the bug**
When the Stats extension is activated and the Update Manager is not, an admin notice shows on every dashboard page. As the screenshots show, the notice is irrelevant to most views. A plugin's dashboard messages should be constrained to their own page(s) and not displayed elsewhere in other dashboard views. There is also no need to have a link to the plugin's view in the notice; that should be a link, also shown below in the screenshots.

**To Reproduce**
1. Install Update Manager
1. Install Stats extension
1. Deactivate Update Manager
1. See rogue dashboard notices

**Expected behavior**
Plugin notices are shown only on their own page(s).

**Screenshots**

**This is where the link to your plugin view goes, rather than a dashboard notice**

![image](https://user-images.githubusercontent.com/12477319/72073041-fafa7f00-32a3-11ea-86cf-d3cc5b0f6fa4.png)

**Admin notices hijacking the dashboard**

![image](https://user-images.githubusercontent.com/12477319/72072158-3136ff00-32a2-11ea-9461-14e1fb9ff71f.png)
![image](https://user-images.githubusercontent.com/12477319/72072214-4ca20a00-32a2-11ea-8075-1d839d05cb9f.png)
![image](https://user-images.githubusercontent.com/12477319/72072265-6c393280-32a2-11ea-89c7-44981e00a455.png)
![image](https://user-images.githubusercontent.com/12477319/72072309-84a94d00-32a2-11ea-9c98-cbb06f96d6bc.png)
![image](https://user-images.githubusercontent.com/12477319/72072336-8f63e200-32a2-11ea-8738-bbb77ea9a9c8.png)

**Comment by xxsimoxx** [comment]
"hijacks" just to be kind!
Fixing in seconds...
Thank you!

**Comment by johnalarcon** [comment]
Yeah, no offense, that's just what we call it. 😄 If you want to use an admin message on the main plugins page, it should be a one-time notification after activation (or better yet, your plugin shouldn't activate without the prerequisite). That would be a good moment to say "You first have to install..." but it should only display there once on the main plugins page. It can still persist on its own page and not be seen as hijacking the dashboard. 👍

**Comment by xxsimoxx** [comment]
I've moved the notice just to the plugin page and added an icon in the plugin page.
Really it should not activate, but I preferred to keep the debug section in a page under tools, it can be useful for developers (that are the target of the plugin).
