### ISSUE TITLE
PHP_INT_MAX used throughout

### ISSUE THREAD

**Issue by johnalarcon** [xxsimoxx/stats-for-update-manager#14]
**Describe the bug**

The `PHP_INT_MAX` constant is used to set priority throughout the code. By using PHP_INT_MAX, you're setting a priority of **9223372036854775807** which is completely unnecessary. This constant should only be used as a priority in _exceptionally rare cases_. I suspect your intention here was to ensure that your Stats menu item appears below all others. However, this is problematic if another menu item must be placed below it – you have to first unhook your functions, hook in the other item(s), then rehook your functions with proper integer values for the priority.

**Solution**

Use actual integers for priority values. Considering that the default priority is **10**, you can use a priority of **100** or even **1000** [here](https://github.com/xxsimoxx/stats-for-update-manager/blob/f077e84937b77086f7f2061acb32d7700fc5b0c3/stats-for-update-manager.php#L72) to keep your item at the bottom of the list. 

**Additional**

For the [7th argument](https://github.com/xxsimoxx/stats-for-update-manager/blob/f077e84937b77086f7f2061acb32d7700fc5b0c3/stats-for-update-manager.php#L235-L243) you are passing PHP_INT_MAX to `add_submenu_page`. Passing a priority here does not work; instead, set a priority (meaning _position_) as described above.

**Comment by xxsimoxx** [comment]
Thank you!
I've seen `PHP_INT_MAX` used often so I blindly took it as a good way.
>For the 7th argument you are passing PHP_INT_MAX to add_submenu_page.

Yes, just discovered it's a WP 5.3 parameter!
