### ISSUE TITLE
Provide a constant or condition to stop tracking

### ISSUE THREAD

**Issue by bahiirwa** [xxsimoxx/stats-for-update-manager#15]
I am coming from a privacy point where on of my plugin users does not want to have their site tracked but I have others who don't mind.

Is there a constant of hook they can use to escape being tracked?

I believe the best place is at `is_safe_url()` or `log_request()`

PS: Thanks for writing this, it is big help as a developer.

**Comment by xxsimoxx** [comment]
It's not a problem to add a filter to `is_safe_url` to let you filter out hosts that opted out. But in this scenario you will have to keep a log of who don't want to be logged. In this way you will store the same data that stats is storing. And have a plugin on your update server to handle this.

An alternative is to upen an issue in Update Manager to add a filter [in UpdateClient](https://github.com/codepotent/Update-Manager/blob/1b0552d146eea55c5b802aebe4ce2d65ae0e0cdb/classes/UpdateClient.class.php#L475) to let you add to the body of the request something like `$body['privacy']='private'` so I can check it out before logging.

What do you think about? I'll do whatever you prefer, even both...

**Comment by bahiirwa** [comment]
If a client added a `define(‘NOTRACKINGSTUM’, true);` can’t you use this as a check in the `safe_url()` to ignore that one domain? I am assuming it makes an array of data.

**Comment by xxsimoxx** [comment]
That constant is defined in the server where CC is running, but SFUM and UM are running on your server and not on the customer's one. The only point of communication is in UpdateClient.class.php that is bundled with CC.

**Comment by xxsimoxx** [comment]
I've done a bit of tests...
If a filter is introduced [here](https://github.com/codepotent/Update-Manager/blob/1b0552d146eea55c5b802aebe4ce2d65ae0e0cdb/classes/UpdateClient.class.php#L494) to filter the value of `$body` and add something like 
`$body['sfum']='no-log'`
when your customer decided to opt-out, then I can add (it's ready) the possibility to skip logging.

In your code you can add something like this:
```
add_filter( 'codepotent_updateclient_pluginslug/pluginslug_body', 'disable_sfum_logging' );
function disable_sfum_logging( $body ){
   if( get_option( 'cc_opt_out' ) === true ){
      $body['sfum']='no-log';
   }
   return $body;
}
```

Tagging @johnalarcon here because Update Manager is likely to be involved with a feature request.

**Comment by johnalarcon** [comment]
I have reviewed the feature request submitted against the Update Manager repo, but, will not be implementing it for the reasons noted there.

https://github.com/codepotent/Update-Manager/issues/29

**Comment by xxsimoxx** [comment]
Stats for UM get the request that the Update Client sends to Update Manager.
if in this request Stats for UM finds `$body['sfum']='no-log';` the request is skipped.
It's now implemented.
