### ISSUE TITLE
Error with uninstall method

### ISSUE THREAD

**Issue by johnalarcon** [xxsimoxx/stats-for-update-manager#2]
# Description

The uninstall method is written and called incorrectly, which causes a couple of issues. The solution is simple, but, as you don't have any contributor docs available, I'm creating this issue instead of the PR. You will find 2 issues referenced here; they are related to one another and will be fixed with the same solution, so, I've combined them as a single issue.

## Issue 1
On activation, a PHP notice is generated, which, in turn, also generates an error in the ClassicPress dashboard:

#### The PHP Notice
> Notice: register_uninstall_hook was called incorrectly. Only a static class method or function can be used in an uninstall hook....

#### The Dashboard Notice
> The plugin generated 419 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

## Issue 2
On uninstallation, because the uninstall method is not actually invoked, an orphaned table is left in the database.

# Steps to reproduce issue 1
1. Enable debugging via config file.
1. Activate the plugin.
1. See the error.

# Steps to reproduce issue 2
1. Uninstall/delete the stats plugin.
1. See the database; table still exists.

# Context
Your current code is calling its uninstall method in the context of your object, `$this`, as a public non-static method. This doesn't work in ClassicPress (or WordPress.)

# Solution
You will need to make 2 changes to fix these issues.

**First**: change [this line](https://github.com/xxsimoxx/stats-for-update-manager/blob/3d6f5b08a4a9077594e9f042965b9f3de81c2c96/stats-for-update-manager.php#L102) to reference the `__CLASS__` magic constant instead of referencing `$this`, as follows:

`register_uninstall_hook(__FILE__, [__CLASS__, 'uninstall']);`

**Second**, change [this line](https://github.com/xxsimoxx/stats-for-update-manager/blob/3d6f5b08a4a9077594e9f042965b9f3de81c2c96/stats-for-update-manager.php#L354) to make the method static, as follows:

`public static function uninstall() {`

**Comment by xxsimoxx** [comment]
Thank you for pointing it out and giving me the solution!

**Comment by xxsimoxx** [comment]
> as you don't have any contributor docs available

It's in my to-do list :-(
But any PR is welcome!

**Comment by johnalarcon** [comment]
> It's in my to-do list :-(

This is super tedious, I know. What I did is to move all my repos from my personal account (johnalarcon) to my organization account (codepotent) ... both are free, so there was no cost. With an org account, you can setup Code of Conduct, contributing and support guidelines, security, issue templates, etc... they apply to all your new repos, so, you never have to do it again. Same for labels...you can specify a bunch of colored labels and they'll be available to all your new repos. Here's the docs if you want to look into it.

1. https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/
2. https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/managing-default-labels-for-repositories-in-your-organization 

> But any PR is welcome!

History tells me that it's never a good idea to submit PRs without guidelines in place. This can lead to rework and wasted time because devs will often say,

> _This code doesn't follow the standards/format/spacing/whatever that we use...so, if you could just fix x, y, and z... then we'll take another look._

I'm happy to submit PRs once you have your docs in place.

**Comment by xxsimoxx** [comment]
The org account seems the smarter solution! Thank you for the hints!
For now I'm trying a very easy policy and keep the personal account, waiting for some spare time!
