### ISSUE TITLE
Inconsistent display of plugin name.

### ISSUE THREAD

**Issue by johnalarcon** [xxsimoxx/stats-for-update-manager#3]
# Description

The stats display is not showing plugin names consistently.

![image](https://user-images.githubusercontent.com/12477319/71599606-66a05780-2b00-11ea-82ae-822dc5a6b7ee.png)

**Comment by xxsimoxx** [comment]
Hi!
This should be the situation where `Update Manager` and `Update Me` are present in Update Manager (they have their own custom post) and `codepotent-syntax-highlighter` don't.
Can you please confirm this?
If I'm right, what do you think is a better way to display names that don't exist in Update Manager?

**Comment by johnalarcon** [comment]
The Syntax Highlighter _does_ have an endpoint in Update Manager. The issue is that your `get_cpt()` method only queries for _published_ posts (simply by virtue of not specifying a `post_status` argument.) You can resolve this by adding an argument to your `get_posts()` call in that method as depicted below. After adding the argument, the names are displayed properly and they are linked to their respective endpoint editor. ⚡️ 

```
private function get_cpt() {
	$data = [];
	if (!$this->um_running) {
		return $data;
	}
	$posts = get_posts([
		'post_type' => $this->um_cpt,
		'post_status' => ['publish', 'pending' ,'draft'], // <----- gets posts in the multiple statuses
		'numberposts' => -1
		]);
	foreach($posts as $post) {
		$meta = get_post_meta($post->ID, 'id', true);
		$data[$meta] = $post->ID;
	}
	return $data;
}
```

> ...what do you think is a better way to display names that don't exist in Update Manager?

If they don't exist in the Update Manager, they probably shouldn't be displayed. ;)

**Comment by xxsimoxx** [comment]
Thank you very much.
Fixed this and disabled displaying statistics if Update Manager is not running. Now it just show debug information.
