### ISSUE TITLE
Add filter for length of time data is stored

### ISSUE THREAD

**Issue by johnalarcon** [xxsimoxx/stats-for-update-manager#8]
**Describe the functions you wish to be added**

In your readme, there is this passage...

> This plugin stores data about plugin updates in a table. You can see/change how much time this data is kept in the first lines of the plugin...

If a user updates your plugin, their edit would be overwritten by the update and the user would have to make the change again (if they remember to). This request is for a filter on that value, which would allow users to change it without the risk of losing their change.

**Have you already some code that could help?**
- [ ] Yes
- [x] No

**Comment by xxsimoxx** [comment]
Sure, I'll do this.
Now the code is:
`private $db_unactive_entry = 'INTERVAL 1 WEEK';`
For me filtering this all can lead to SQL troubles, I was thinking about:
1. Filtering just the number
2. Moving from `WEEK` to `DAY` for more granularity
But I'd like your feedback about it!

**Comment by johnalarcon** [comment]
I think `DAY` is more versatile for the actual values people might use (1 day, 3 days, 10 days, 30 days) which don't neatly fit under a `WEEK` format.

**Comment by johnalarcon** [comment]
PS. I don't actually need this feature myself...  I'm just thinking about your other users who may want to edit your core files. :) They'll be grateful that you added the filter.

**Comment by xxsimoxx** [comment]
> your other users who may want to edit your core files. :)

Yes, really not good :-)
I like this enhancement! Thank you!
I've just worked it out and (likely tomorrow) after some test I'll commit those changes.
